GET http://localhost:8000/products/ HTTP/1.1

###

GET http://localhost:8000/products/26/ HTTP/1.1

###

DELETE http://localhost:8000/products/26/ HTTP/1.1

###

PUT http://localhost:8000/products/26/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzgxMjM4MDYwLCJpYXQiOjE3ODEyMzc3NjAsImp0aSI6IjdhMjQ1OGJkNWQwYTQwZjRiNWY2OWRlNzVkYTA0ZWQwIiwidXNlcl9pZCI6IjEifQ.pfiqmgcaoH7m7IMHTYv-ah-koBeiwZ360Jn3QjlTn4A

{
    "name": "Television",
    "price": 300.00,
    "stock": 14,
    "description": "An amazing new TV"
}

###

POST http://localhost:8000/products/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzgwODAwNDgyLCJpYXQiOjE3ODA4MDAxODIsImp0aSI6IjBmMTVmYTU2MWZlYTQ4N2Q5ZDg4NmFhNjIyYzAzZDQ3IiwidXNlcl9pZCI6IjIifQ.XZJiXYli94eylB4uc8BBemn4poR6G2IkpGwN7Ev1owc

{
    "name": "Television",
    "price": 300.00,
    "stock": 14,
    "description": "An amazing new TV"
}

###

POST http://localhost:8000/api/token/ HTTP/1.1
Content-Type: application/json

{
    "username": "john-doe",
    "password": "admin"
}

###

GET http://localhost:8000/user-orders/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzgwODAwNDgyLCJpYXQiOjE3ODA4MDAxODIsImp0aSI6IjBmMTVmYTU2MWZlYTQ4N2Q5ZDg4NmFhNjIyYzAzZDQ3IiwidXNlcl9pZCI6IjIifQ.XZJiXYli94eylB4uc8BBemn4poR6G2IkpGwN7Ev1owc

###

POST http://localhost:8000/api/token/ HTTP/1.1
Content-Type: application/json

{
    "username": "admin",
    "password": "test"
}

###

POST http://localhost:8000/api/token/refresh/ HTTP/1.1
Content-Type: application/json

{
    "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc4MDkwMTExMCwiaWF0IjoxNzgwODE0NzEwLCJqdGkiOiJlOGQ3NWNkZTdmZTI0YzU0OTg3MmM3NTczMTViYmFjMSIsInVzZXJfaWQiOiIxIn0.d6cMTz6JCu2qiUEHGhSshiU-wXrgTOGLfVsj7o_OkL4"
}